version: '3'

services:
  Practice:
    image: laba_module1
    build:
      context: ./Practice
      dockerfile: ./Dockerfile
    container_name: module1
    ports:
      - 5001:80

  Module2:
    image: laba_module2
    build:
      context: ./Module2
      dockerfile: ./Dockerfile
    container_name: module2
    ports:
      - 5000:80
